# Site settings
title: John Murray
email: me@johnmurray.io
description: <
  Random thoughts of John Murray
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.johnmurray.io"
# Build settings
markdown: kramdown
exclude: [vendor, config.ru, Gemfile, Gemfile.lock, Procfile]
include: [blog_files]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "log"
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      category: "draft"
      layout: "post"
